CourseShuffle/Controllers/CourseShuffle/CoursesController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using CoureShuffle.Data.DataContext.DataContext;
using CourseShuffle.Data.Factory.FactoryData;
using CourseShuffle.Data.Objects.Entities;
using CourseShuffle.Data.Service.Enum;

namespace CourseShuffle.Controllers.CourseShuffle
{
    public class CoursesController : Controller
    {
        private readonly CourseDataContext _db = new CourseDataContext();

        // GET: Courses
        public ActionResult Index()
        {
            var courses = _db.Courses.Include(c => c.Department).Include(c => c.Level);
            return View(courses.ToList());
        }

        public ActionResult ViewCoursesForDepartment(long id)
        {
            var courses = new CourseFactory().GetAllCoursesForADepartment(id);
            return View("DeparmentCourses", courses);
        }
        public ActionResult GetCoursesForLecturer(long lecturerId, long departmentId)
        {
            var courses = new CourseFactory().GetAllCoursesForADepartment(departmentId);
            var lecturerCourses = courses.Where(n => n.AppUserId == lecturerId);
            return View("Index", lecturerCourses);
        }
        public ActionResult GetCoursesForFacilitator(long departmentId)
        {
            var courses = new CourseFactory().GetAllCoursesForADepartment(departmentId);
            return View("Index", courses);
        }


        public ActionResult ViewCoursesForLevel(long levelId, long departmentId)
        {
            var courses = new CourseFactory().GetAllCoursesForALevel(levelId, departmentId);
            return View("LevelCorses", courses);
        }


        // GET: Courses/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var courses = _db.Courses.Find(id);
            if (courses == null)
                return HttpNotFound();
            return View(courses);
        }

        // GET: Courses/Create
        public ActionResult Create(long? id, long? departmentId)
        {
            if (id <= 0)
                id = 0;
            ViewBag.DepartmentId = new SelectList(_db.Departments, "DepartmentId", "Name");
            ViewBag.Level = id ?? 0;
            ViewBag.Department = departmentId ?? 0;
            ViewBag.LevelId = new SelectList(_db.Levels, "LevelId", "Name");
            ViewBag.AppUserId = new SelectList(_db.AppUsers.Where(n => n.Role == UserType.Lecturer.ToString()),
                "AppUserId", "DisplayName");
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(
            [Bind(Include = "CoursesId,CourseName,CourseCode,CreditUnit,AppUserId,DepartmentId")] Courses courses,
            FormCollection collectedValues)
        {
            if (ModelState.IsValid)
            {
                var loggedinuser = Session["courseshuffleloggedinuser"] as AppUser;
                if (loggedinuser != null)
                {
                    var levelId = Convert.ToInt64(collectedValues["levelId"]);
                    var departmentId = Convert.ToInt64(collectedValues["departmentId"]);
                    if (collectedValues["levelId"] == null)
                        levelId = Convert.ToInt64(collectedValues["Level"]);
                    if (collectedValues["departmentId"] == null)
                        departmentId = Convert.ToInt64(collectedValues["Department"]);

                    courses.LevelId = levelId;
                    courses.DepartmentId = departmentId;
                    courses.Semester = typeof(SemesterType).GetEnumName(int.Parse(collectedValues["Semester"]));
                    courses.DateCreated = DateTime.Now;
                    courses.DateLastModified = DateTime.Now;
                    courses.LastModifiedBy = loggedinuser.AppUserId;
                    courses.CreatedBy = loggedinuser.AppUserId;
                    _db.Courses.Add(courses);
                    _db.SaveChanges();
                    TempData["course"] = "A new course has been created successfully!";
                    TempData["notificationtype"] = NotificationType.Success.ToString();
                    return RedirectToAction("ViewCoursesForLevel", new {levelId, departmentId});
                }
                TempData["course"] = "Your session has expired,Login Again!";
                TempData["notificationtype"] = NotificationType.Info.ToString();
            }

            ViewBag.DepartmentId = new SelectList(_db.Departments, "DepartmentId", "Name", courses.DepartmentId);
            ViewBag.LevelId = new SelectList(_db.Levels, "LevelId", "Name", courses.LevelId);
            ViewBag.AppUserId = new SelectList(_db.AppUsers.Where(n => n.Role == UserType.Lecturer.ToString()),
                "AppUserId", "DisplayName");
            return View(courses);
        }

        // GET: Courses/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var courses = _db.Courses.Find(id);
            if (courses == null)
                return HttpNotFound();
            return View(courses);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(
            [Bind(Include = "CoursesId,CourseName,CourseCode,CreditUnit,AppUserId,LevelId,DepartmentId,CreatedBy")] Courses courses, FormCollection collectedValues)
        {
            if (ModelState.IsValid)
            {
                var loggedinuser = Session["courseshuffleloggedinuser"] as AppUser;
                if (loggedinuser != null)
                {
                    courses.DateLastModified = DateTime.Now;
                    courses.LastModifiedBy = loggedinuser.AppUserId;
                    courses.DateCreated = Convert.ToDateTime(collectedValues["DateCreated"]);
                    _db.Entry(courses).State = EntityState.Modified;
                    _db.SaveChanges();
                    TempData["course"] = "A new course has been modified successfully!";
                    TempData["notificationtype"] = NotificationType.Success.ToString();
                    return RedirectToAction("Index");
                }
                TempData["course"] = "Your session has expired,Login Again!";
                TempData["notificationtype"] = NotificationType.Info.ToString();
            }

            //ViewBag.DepartmentId = new SelectList(_db.Departments, "DepartmentId", "Name", courses.DepartmentId);
            //ViewBag.LevelId = new SelectList(_db.Levels, "LevelId", "Name", courses.LevelId);
            return View(courses);
        }

        // GET: Courses/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var courses = _db.Courses.Find(id);
            if (courses == null)
                return HttpNotFound();
            return View(courses);
        }

        // POST: Courses/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            var courses = _db.Courses.Find(id);
            _db.Courses.Remove(courses);
            _db.SaveChanges();
            TempData["course"] = "A  course has been deleted successfully!";
            TempData["notificationtype"] = NotificationType.Success.ToString();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

CourseShuffle/Controllers/CourseShuffle/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CoureShuffle.Data.DataContext.DataContext;
using CourseShuffle.Data.Objects.Entities;
using CourseShuffle.Data.Service.Enum;
using CourseShuffle.Data.Service.FileUploader;

namespace CourseShuffle.Controllers.CourseShuffle
{
    public class ProjectsController : Controller
    {
        private ProjectDataContext _db = new ProjectDataContext();

        // GET: Projects
        public ActionResult Index()
        {
            var projects = _db.Projects.Include(p => p.Session);
            return View(projects.ToList());
        }
        // GET: Projects
        public ActionResult GetProjectsForDepartment(long departmentId)
        {
            var projects = _db.Projects.Include(p => p.Session).Where(n=>n.DepartmentId == departmentId );
            return View("Index",projects.ToList());
        }

        // GET: Projects/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = _db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // GET: Projects/Create
        public ActionResult Create()
        {
            ViewBag.SessionId = new SelectList(_db.Sessions, "SessionId", "Name");
            ViewBag.DepartmentId = new SelectList(_db.Departments, "DepartmentId", "Name");
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProjectId,Title,Author,StartDate,EndDate,CategoryId,SessionId,DepartmentId")] Project project,FormCollection collectedValues)
        {
            var loggedinuser = Session["courseshuffleloggedinuser"] as AppUser;
            if (ModelState.IsValid)
            {
                if (loggedinuser != null)
                {
                    HttpPostedFileBase document = Request.Files["document"];
                    project.Document = new FileUploader().UploadFile(document,
    UploadType.ProjectDocument.ToString());
                    project.DateCreated = DateTime.Now;
                    project.DateLastModified = DateTime.Now;
                    project.CreatedBy = loggedinuser.AppUserId;
                    project.LastModifiedBy = loggedinuser.AppUserId;
                    _db.Projects.Add(project);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
                TempData["project"] = "Your session has expired,Login Again!";
                TempData["notificationtype"] = NotificationType.Info.ToString();
                return RedirectToAction("Index");
            }

            ViewBag.SessionId = new SelectList(_db.Sessions, "SessionId", "Name", project.SessionId);
            ViewBag.DepartmentId = new SelectList(_db.Departments, "DepartmentId", "Name", project.DepartmentId);
            return View(project);
        }

        // GET: Projects/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = _db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            ViewBag.SessionId = new SelectList(_db.Sessions, "SessionId", "Name", project.SessionId);
            ViewBag.DepartmentId = new SelectList(_db.Departments, "DepartmentId", "Name",project.DepartmentId);
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProjectId,Title,Author,CategoryId,DepartmentId,Document,SessionId,CreatedBy")] Project project,FormCollection collectedValues)
        {
            var loggedinuser = Session["courseshuffleloggedinuser"] as AppUser;
            if (ModelState.IsValid)
            {
                if (loggedinuser != null)
                {
                    project.StartDate = Convert.ToDateTime(collectedValues["StartDate"]);
                    project.EndDate = Convert.ToDateTime(collectedValues["EndDate"]);
                    project.DateCreated = Convert.ToDateTime(collectedValues["DateCreated"]);
                    project.DateLastModified = DateTime.Now;
                    project.LastModifiedBy = loggedinuser.AppUserId;
                    _db.Entry(project).State = EntityState.Modified;
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
                TempData["project"] = "Your session has expired,Login Again!";
                TempData["notificationtype"] = NotificationType.Info.ToString();
                return RedirectToAction("Index");
            }
    
                ViewBag.SessionId = new SelectList(_db.Sessions, "SessionId", "Name", project.SessionId);
            ViewBag.DepartmentId = new SelectList(_db.Departments, "DepartmentId", "Name", project.DepartmentId);
            return View(project);
        }

        // GET: Projects/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = _db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Project project = _db.Projects.Find(id);
            _db.Projects.Remove(project);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CourseShuffle/Views/Shared/_Layout.cshtml
@using CourseShuffle.Data.Objects.Entities
@using CourseShuffle.Data.Service.Enum
@{
    var loggedinuser = Session["courseshuffleloggedinuser"] as AppUser;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="~/UploadedFiles/cousesufflelogo (2).png" type="image/x-icon/">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("css", false)

    <style>
        .navbar-login {
            padding: 10px;
            padding-bottom: 0px;
            width: 305px;
        }

        .navbar-login-session {
            padding: 10px;
            padding-bottom: 0px;
            padding-top: 0px;
        }

        .icon-size { font-size: 87px; }
    </style>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Course Shuffle", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @if (loggedinuser != null)
                {
                    if (loggedinuser.Role == UserType.Administrator.ToString())
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                AppUser
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="@Url.Action("Index", "AppUsers")">Users</a>
                                </li>
                            </ul>
                        </li>
                    }
                    if (loggedinuser.Role == UserType.Administrator.ToString())
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Faculty
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="@Url.Action("Index", "Faculties")">Faculties</a>
                                </li>
                            </ul>
                        </li>
                    }
                }
                @*@if ((loggedinuser != null) && (loggedinuser.Role == UserType.Administrator.ToString()))
                {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Departments
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="@Url.Action("Index", "Departments")">Departments</a>
                            </li>
                        </ul>
                    </li>
                }*@
                @if ((loggedinuser != null) && (loggedinuser.Role == UserType.Lecturer.ToString()))
                {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            My Course(s)

                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            @if (loggedinuser.Role == UserType.Lecturer.ToString())
                            {
                                <li>
                                    <a href="@Url.Action("GetCoursesForLecturer", "Courses", new {lecturerId = loggedinuser.AppUserId, departmentId = loggedinuser.DepartmentId})">My Course(s)</a>
                                </li>
                            }
                            @if (loggedinuser.Role == UserType.Facilitator.ToString())
                            {
                                <li>
                                    <a href="@Url.Action("Index", "Courses", new {id = loggedinuser.DepartmentId})">Course(s)</a>
                                </li>
                            }

                        </ul>
                    </li>
                }
                @if ((loggedinuser != null) && (loggedinuser.Role == UserType.Administrator.ToString()))
                {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Cofigurations

                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            @if (loggedinuser.Role == UserType.Administrator.ToString())
                            {
                                <li>
                                    <a href="@Url.Action("Index", "Sessions")">Session Management</a>
                                </li>
                            }

                            @if (loggedinuser.Role == UserType.Administrator.ToString())
                            {
                                <li>
                                    <a href="@Url.Action("Index", "Categories")">Category Management</a>
                                </li>
                            }
                            @if (loggedinuser.Role == UserType.Administrator.ToString())
                            {
                                <li>
                                    <a href="@Url.Action("Index", "Projects")">Project Management</a>
                                </li>
                            }
                        </ul>
                    </li>
                }

            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", false)
</body>
</html>

CourseShuffle/Views/Shared/_LayoutMain.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/bootstrap.css" rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" href="../../Content/bootstrap-theme.min.css"/>
    <link href="~/AppTheme/assets/css/front.css" type="text/css" rel="stylesheet" media="screen">
    <link rel="shortcut icon" href="~/UploadedFiles/cousesufflelogo (2).png" type="image/x-icon/">
    <title>@ViewBag.Title</title>
    @*@Styles.Render("~/Content/css")*@
    @RenderSection("css", false)
    <style type="text/css">
        .grad {
            background-color: #1ea89c;
            float: right;
            height: 200px;
            width: 200px;
        }

        .slim {
            text-align: center;
            width: 200px;
        }

        li > a:hover {
            color: #fff;
            text-decoration: none;
        }

        .d_icon {
            color: #2b3d51;
            font-size: 80px;
            margin-left: 30%;
            margin-right: 30%;
            margin-top: 5%;
        }

        .da_icon {
            color: #2b3d51;
            margin-left: 20%;
            margin-right: 35%;
            text-align: center;
        }

        .myfont {
            font-family: Tw Cen Mt;
            font-size: 15px;
        }

        li > a:focus {
            color: #fff;
            text-decoration: none;
        }
    </style>


</head>
<body>
@RenderBody()


@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", false)
</body>
</html>