CourseShuffle/Controllers/CourseShuffle/CoursesController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using CoureShuffle.Data.DataContext.DataContext;
using CourseShuffle.Data.Factory.FactoryData;
using CourseShuffle.Data.Objects.Entities;
using CourseShuffle.Data.Service.Enum;

namespace CourseShuffle.Controllers.CourseShuffle
{
    public class CoursesController : Controller
    {
        private readonly CourseDataContext _db = new CourseDataContext();

        // GET: Courses
        public ActionResult Index()
        {
            var courses = _db.Courses.Include(c => c.Department).Include(c => c.Level);
            return View(courses.ToList());
        }

        public ActionResult ViewCoursesForDepartment(long id)
        {
            var courses = new CourseFactory().GetAllCoursesForADepartment(id);
            return View("DeparmentCourses", courses);
        }
        public ActionResult GetCoursesForLecturer(long lecturerId, long departmentId)
        {
            var courses = new CourseFactory().GetAllCoursesForADepartment(departmentId);
            var lecturerCourses = courses.Where(n => n.AppUserId == lecturerId);
            return View("Index", lecturerCourses);
        }
        public ActionResult GetCoursesForFacilitator(long departmentId)
        {
            var courses = new CourseFactory().GetAllCoursesForADepartment(departmentId);
            return View("Index", courses);
        }


        public ActionResult ViewCoursesForLevel(long levelId, long departmentId)
        {
            var courses = new CourseFactory().GetAllCoursesForALevel(levelId, departmentId);
            return View("LevelCorses", courses);
        }


        // GET: Courses/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var courses = _db.Courses.Find(id);
            if (courses == null)
                return HttpNotFound();
            return View(courses);
        }

        // GET: Courses/Create
        public ActionResult Create(long? id, long? departmentId)
        {
            if (id <= 0)
                id = 0;
            ViewBag.DepartmentId = new SelectList(_db.Departments, "DepartmentId", "Name");
            ViewBag.Level = id ?? 0;
            ViewBag.Department = departmentId ?? 0;
            ViewBag.LevelId = new SelectList(_db.Levels, "LevelId", "Name");
            ViewBag.AppUserId = new SelectList(_db.AppUsers.Where(n => n.Role == UserType.Lecturer.ToString()),
                "AppUserId", "DisplayName");
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(
            [Bind(Include = "CoursesId,CourseName,CourseCode,CreditUnit,AppUserId,DepartmentId")] Courses courses,
            FormCollection collectedValues)
        {
            if (ModelState.IsValid)
            {
                var loggedinuser = Session["courseshuffleloggedinuser"] as AppUser;
                if (loggedinuser != null)
                {
                    var levelId = Convert.ToInt64(collectedValues["levelId"]);
                    var departmentId = Convert.ToInt64(collectedValues["departmentId"]);
                    if (collectedValues["levelId"] == null)
                        levelId = Convert.ToInt64(collectedValues["Level"]);
                    if (collectedValues["departmentId"] == null)
                        departmentId = Convert.ToInt64(collectedValues["Department"]);

                    courses.LevelId = levelId;
                    courses.DepartmentId = departmentId;
                    courses.Semester = typeof(SemesterType).GetEnumName(int.Parse(collectedValues["Semester"]));
                    courses.DateCreated = DateTime.Now;
                    courses.DateLastModified = DateTime.Now;
                    courses.LastModifiedBy = loggedinuser.AppUserId;
                    courses.CreatedBy = loggedinuser.AppUserId;
                    _db.Courses.Add(courses);
                    _db.SaveChanges();
                    TempData["course"] = "A new course has been created successfully!";
                    TempData["notificationtype"] = NotificationType.Success.ToString();
                    return RedirectToAction("ViewCoursesForLevel", new {levelId, departmentId});
                }
                TempData["course"] = "Your session has expired,Login Again!";
                TempData["notificationtype"] = NotificationType.Info.ToString();
            }

            ViewBag.DepartmentId = new SelectList(_db.Departments, "DepartmentId", "Name", courses.DepartmentId);
            ViewBag.LevelId = new SelectList(_db.Levels, "LevelId", "Name", courses.LevelId);
            ViewBag.AppUserId = new SelectList(_db.AppUsers.Where(n => n.Role == UserType.Lecturer.ToString()),
                "AppUserId", "DisplayName");
            return View(courses);
        }

        // GET: Courses/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var courses = _db.Courses.Find(id);
            if (courses == null)
                return HttpNotFound();
            return View(courses);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(
            [Bind(Include = "CoursesId,CourseName,CourseCode,CreditUnit,AppUserId,LevelId,DepartmentId,CreatedBy")] Courses courses, FormCollection collectedValues)
        {
            if (ModelState.IsValid)
            {
                var loggedinuser = Session["courseshuffleloggedinuser"] as AppUser;
                if (loggedinuser != null)
                {
                    courses.DateLastModified = DateTime.Now;
                    courses.LastModifiedBy = loggedinuser.AppUserId;
                    courses.DateCreated = Convert.ToDateTime(collectedValues["DateCreated"]);
                    _db.Entry(courses).State = EntityState.Modified;
                    _db.SaveChanges();
                    TempData["course"] = "A new course has been modified successfully!";
                    TempData["notificationtype"] = NotificationType.Success.ToString();
                    return RedirectToAction("Index");
                }
                TempData["course"] = "Your session has expired,Login Again!";
                TempData["notificationtype"] = NotificationType.Info.ToString();
            }

            //ViewBag.DepartmentId = new SelectList(_db.Departments, "DepartmentId", "Name", courses.DepartmentId);
            //ViewBag.LevelId = new SelectList(_db.Levels, "LevelId", "Name", courses.LevelId);
            return View(courses);
        }

        // GET: Courses/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var courses = _db.Courses.Find(id);
            if (courses == null)
                return HttpNotFound();
            return View(courses);
        }

        // POST: Courses/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            var courses = _db.Courses.Find(id);
            _db.Courses.Remove(courses);
            _db.SaveChanges();
            TempData["course"] = "A  course has been deleted successfully!";
            TempData["notificationtype"] = NotificationType.Success.ToString();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

CourseShuffle/Controllers/CourseShuffle/DepartmentsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using CoureShuffle.Data.DataContext.DataContext;
using CourseShuffle.Data.Factory.FactoryData;
using CourseShuffle.Data.Objects.Entities;
using CourseShuffle.Data.Service.Enum;

namespace CourseShuffle.Controllers.CourseShuffle
{
    public class DepartmentsController : Controller
    {
        private readonly DepartmentDataContext _db = new DepartmentDataContext();

        // GET: Departments
        public ActionResult Index()
        {
            var departments = _db.Departments.Include(d => d.Faculty);
            return View(departments.ToList());
        }

        // GET: Departments/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var department = _db.Departments.Find(id);
            if (department == null)
                return HttpNotFound();
            return View(department);
        }

        public ActionResult ViewDepartmentForFaculty(long id)
        {
            var departments = new DepartmentFactory().GetAllDepartmentsForAFaculty(id);
            return View("FacultyDepartments", departments);
        }

        // GET: Departments/Create
        public ActionResult Create(long? id)
        {
            if (id <= 0)
                id = 0;
            ViewBag.FacultyId = new SelectList(_db.Faculties, "FacultyId", "Name");
            ViewBag.Faculty = id ?? 0;

            return View();
        }

        // POST: Departments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DepartmentId,Name,Description")] Department department,
            FormCollection collectedValues)
        {
            if (ModelState.IsValid)
            {
                var loggedinuser = Session["courseshuffleloggedinuser"] as AppUser;
                var type = typeof(SubscriptionType).GetEnumName(int.Parse(collectedValues["Type"]));
                if (loggedinuser != null)
                {
                    var facultyId = Convert.ToInt64(collectedValues["FacultyId"]);
                    if (collectedValues["FacultyId"] == null)
                        facultyId = Convert.ToInt64(collectedValues["Faculty"]);
                    if (type == SubscriptionType.None.ToString())
                    {
                        department.SubscriptionStartDate = null;
                        department.SubscriptionEndDate = null;
                        department.SubscriptionType = type;
                    }
                    if (type == SubscriptionType.SingleSemester.ToString())
                    {
                        department.SubscriptionStartDate = DateTime.Now;
                        department.SubscriptionEndDate = DateTime.Now.AddMonths(6);
                        department.SubscriptionType = type;
                    }
                    if (type == SubscriptionType.CompleteSession.ToString())
                    {
                        department.SubscriptionStartDate = DateTime.Now;
                        department.SubscriptionEndDate = DateTime.Now.AddMonths(12);
                        department.SubscriptionType = type;
                    }

                    department.FacultyId = facultyId;

                    department.DateCreated = DateTime.Now;
                    department.DateLastModified = DateTime.Now;
                    department.CreatedBy = loggedinuser.AppUserId;
                    department.LastModifiedBy = loggedinuser.AppUserId;
                    _db.Departments.Add(department);
                    _db.SaveChanges();
                    TempData["department"] = "A new department has been created successfully!";
                    TempData["notificationtype"] = NotificationType.Info.ToString();
                    return RedirectToAction("Index");
                }
                TempData["department"] = "Your session has expired,Login Again!";
                TempData["notificationtype"] = NotificationType.Info.ToString();
            }

            ViewBag.FacultyId = new SelectList(_db.Faculties, "FacultyId", "Name", department.FacultyId);
            return View(department);
        }

        // GET: Departments/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var department = _db.Departments.Find(id);
            if (department == null)
                return HttpNotFound();
            ViewBag.FacultyId = new SelectList(_db.Faculties, "FacultyId", "Name", department.FacultyId);
            return View(department);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(
            [Bind(Include = "DepartmentId,Name,Description,FacultyId,CreatedBy,SubscriptionStartDate,SubscriptionEndDate,SubscriptionType")] Department department,
            FormCollection collectedValues)
        {
            if (ModelState.IsValid)
            {
                var type = typeof(SubscriptionType).GetEnumName(int.Parse(collectedValues["Type"]));
                var loggedinuser = Session["courseshuffleloggedinuser"] as AppUser;
                if (loggedinuser != null)
                {
                    if (DateTime.Now > department.SubscriptionEndDate)
                    {
                        if (type == SubscriptionType.None.ToString())
                        {
                            department.SubscriptionStartDate = null;
                            department.SubscriptionEndDate = null;
                            department.SubscriptionType = type;
                        }
                        if (type == SubscriptionType.SingleSemester.ToString())
                        {
                            department.SubscriptionStartDate = DateTime.Now;
                            department.SubscriptionEndDate = DateTime.Now.AddMonths(6);
                            department.SubscriptionType = type;
                        }
                        if (type == SubscriptionType.CompleteSession.ToString())
                        {
                            department.SubscriptionStartDate = DateTime.Now;
                            department.SubscriptionEndDate = DateTime.Now.AddMonths(12);
                            department.SubscriptionType = type;
                        }
                    }

                    department.DateCreated = Convert.ToDateTime(collectedValues["DateCreated"]);
                    department.DateLastModified = DateTime.Now;
                    department.LastModifiedBy = loggedinuser.AppUserId;
                    _db.Entry(department).State = EntityState.Modified;
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
                TempData["department"] = "Your session has expired,Login Again!";
                TempData["notificationtype"] = NotificationType.Info.ToString();
            }
            ViewBag.FacultyId = new SelectList(_db.Faculties, "FacultyId", "Name", department.FacultyId);
            return View(department);
        }

        // GET: Departments/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var department = _db.Departments.Find(id);
            if (department == null)
                return HttpNotFound();
            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            var department = _db.Departments.Find(id);
            _db.Departments.Remove(department);
            _db.SaveChanges();
            TempData["department"] = "A department has been deleted successfully!";
            TempData["notificationtype"] = NotificationType.Success.ToString();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

CourseShuffle/Views/Departments/Create.cshtml
@using CourseShuffle.Data.Service.Enum
@model CourseShuffle.Data.Objects.Entities.Department

@{
    ViewBag.Title = "Create";
    long facultyId = ViewBag.Faculty;
}

<h2>Create</h2>
@section css{
    <link href="~/Scripts/plugins/Form/css/select2.css" rel="stylesheet"/>
}
@if (TempData["department"] != null)
{
    if (TempData["notificationtype"].Equals(NotificationType.Success.ToString()))
    {
        <div class="alert alert-success alert-dismissable" style="height: 30px">@TempData["department"]</div>
    }
    else if (TempData["notificationtype"].Equals(NotificationType.Danger.ToString()))
    {
        <div class="alert alert-danger alert-dismissable" style="height: 30px">@TempData["department"]</div>
    }
    else if (TempData["notificationtype"].Equals(NotificationType.Info.ToString()))
    {
        <div class="alert alert-info alert-dismissable" style="height: 30px">@TempData["department"]</div>
    }
}
<div class="container">
    <div class="row">
        <div class="panel panel-flat">

            <div class="panel-body">
                <div class="col-md-12">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        {
                            facultyId = ViewBag.Faculty;
                            @Html.Hidden("Faculty", facultyId)
                        }
                        <div class="form-horizontal">
                            <h4>Department</h4>
                            <hr/>
                            @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                            <div class="form-group col-md -12">
                                @Html.LabelFor(model => model.Name, new {@class = "control-label col-md-3"})
                                <div class="col-sm-6 col-md-9">
                                    @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
                                    @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
                                </div>
                            </div>

                            <div class="form-group col-md -12">
                                @Html.LabelFor(model => model.Description, new {@class = "control-label col-md-3"})
                                <div class="col-sm-6 col-md-9">
                                    @Html.EditorFor(model => model.Description, new {htmlAttributes = new {@class = "form-control"}})
                                    @Html.ValidationMessageFor(model => model.Description, "", new {@class = "text-danger"})
                                </div>
                            </div>
                            @if ((facultyId == null) || (facultyId <= 0))
                            {
                                <div class="form-group col-md -12">
                                    @Html.LabelFor(model => model.FacultyId, "Faculty", new {@class = "control-label col-md-3"})
                                    <div class="col-sm-6 col-md-9">
                                        @Html.DropDownList("FacultyId", null, new {@class = "form-control select-dropdown"})
                                        @Html.ValidationMessageFor(model => model.FacultyId, "", new {@class = "text-danger"})
                                    </div>
                                </div>
                            }
                            <div class="form-group col-md-12">
                                @Html.LabelFor(model => model.SubscriptionType, new {@class = "control-label col-md-3"})
                                <div class="col-sm-6 col-md-9">
                                    @Html.DropDownList("Type", EnumHelper.GetSelectList(typeof(SubscriptionType)), "select a subsciption Type", new {@class = "form-control select-dropdown", id = "role"})
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    @if (ViewBag.Faculty != null)
                                    {
                                        <a href="@Url.Action("Index", "Faculties")" class="btn btn-default pull-left">Cancel</a>
                                    }
                                    else
                                    {
                                        <a href="@Url.Action("Index", "Departments")" class="btn btn-default pull-left">Cancel</a>
                                    }

                                    <input type="submit" value="Create" class="btn btn-primary pull-right"/>
                                </div>
                            </div>
                        </div>
                    }

                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script src="~/Scripts/plugins/Form/js/select2.min.js"></script>
    <script>
        $(document)
            .ready(function() {

                // Init select2 for dropdown select
                $('.select-dropdown').select2();

            })
    </script>
}

CourseShuffle/Views/Departments/Edit.cshtml
@using CourseShuffle.Data.Service.Enum
@model CourseShuffle.Data.Objects.Entities.Department

@{
    ViewBag.Title = "Edit";
}

<h2></h2>
@section css{
    <link href="~/Scripts/plugins/Form/css/select2.css" rel="stylesheet"/>
}
@if (TempData["department"] != null)
{
    if (TempData["notificationtype"].Equals(NotificationType.Success.ToString()))
    {
        <div class="alert alert-success alert-dismissable" style="height: 30px">@TempData["department"]</div>
    }
    else if (TempData["notificationtype"].Equals(NotificationType.Danger.ToString()))
    {
        <div class="alert alert-danger alert-dismissable" style="height: 30px">@TempData["department"]</div>
    }
    else if (TempData["notificationtype"].Equals(NotificationType.Info.ToString()))
    {
        <div class="alert alert-info alert-dismissable" style="height: 30px">@TempData["department"]</div>
    }
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Department</h4>
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        @Html.HiddenFor(model => model.DepartmentId)
        @Html.HiddenFor(model => model.DateCreated)
        @Html.HiddenFor(model => model.CreatedBy)
        @Html.HiddenFor(model => model.SubscriptionEndDate)
        @Html.HiddenFor(model => model.SubscriptionType)
        @Html.HiddenFor(model => model.SubscriptionStartDate)

        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.Name, new {@class = "control-label col-md-3"})
            <div class="col-md-9">
                @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.Description, new {@class = "control-label col-md-3"})
            <div class="col-md-9">
                @Html.EditorFor(model => model.Description, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Description, "", new {@class = "text-danger"})
            </div>
        </div>
        @if (DateTime.Now > Model.SubscriptionEndDate)
        {
            <div class="form-group col-md-12">
                @Html.LabelFor(model => model.SubscriptionType, new {@class = "control-label col-md-3"})
                <div class="col-sm-6 col-md-9">
                    @Html.DropDownList("Type", EnumHelper.GetSelectList(typeof(SubscriptionType)), "select a subsciption Type", new {@class = "form-control select-dropdown", id = "role"})
                </div>
            </div>
        }
        <div class="row">
            <div class="col-md-12">
                @Html.ActionLink("Back to List", "Index", null, new {@class = "btn btn-default"})
                <input type="submit" value="Save" class="btn btn-primary"/>
            </div>
        </div>
    </div>
}
@section scripts{
    <script src="~/Scripts/plugins/Form/js/select2.min.js"></script>
    <script>
        $(document)
            .ready(function() {

                // Init select2 for dropdown select
                $('.select-dropdown').select2();
            })
    </script>
}

CourseShuffle/Views/Departments/FacultyDepartments.cshtml
@using CourseShuffle.Data.Factory.FactoryData
@using CourseShuffle.Data.Objects.Entities
@model IEnumerable<CourseShuffle.Data.Objects.Entities.Department>

@{
    ViewBag.Title = "Index";
    var levels = new LevelFactory().GetAllLevels();
}
@{
    var levelList = levels as IList<Level> ?? levels.ToList();
}
<h2></h2>
@section css{
    <link href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" rel="stylesheet"/>
}


<p>
    @Html.ActionLink("Create New", "Create", null, new {@class = "btn btn-success"})
</p>
<table class="table table-condensed table-hover" id="datatable">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>Action</th>
    </tr>
    </thead>


    @foreach (var item in Model)
    {
        <tbody>
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {id = item.DepartmentId}, new {@class = "btn btn-primary"}) |
                @Html.ActionLink("Details", "Details", new {id = item.DepartmentId}, new {@class = "btn btn-default"}) |
                @Html.ActionLink("Delete", "Delete", new {id = item.DepartmentId}, new {@class = "btn btn-danger"})|
                <div class="btn-group">
                    <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-cogs"></i>
                        View Course(s) <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu text-left">
                        @foreach (var level in levelList)
                        {
                            <li>
                                <a href="@Url.Action("ViewCoursesForLevel", "Courses", new {levelId = level.LevelId, departmentId = item.DepartmentId})">
                                    <i class="fa fa-file-text-o"></i> @level.Name
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </td>
        </tr>
        </tbody>
    }

</table>
@section scripts {

    <script src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <script>
        $(document)
            .ready(function() {
                $('#datatable').DataTable();
            });

    </script>
}

CourseShuffle/Views/Departments/Index.cshtml
@using CourseShuffle.Data.Factory.FactoryData
@using CourseShuffle.Data.Objects.Entities
@using CourseShuffle.Data.Service.Enum
@model IEnumerable<CourseShuffle.Data.Objects.Entities.Department>

@{
    ViewBag.Title = "Index";
    var levels = new LevelFactory().GetAllLevels();
}
@{
    var levelList = levels as IList<Level> ?? levels.ToList();
    var loggedinuser = Session["courseshuffleloggedinuser"] as AppUser;
}
@section css{
    <link href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" rel="stylesheet"/>
}

<h2></h2>

<p>

    @{
        Department first = null;
        foreach (var n in Model)
        {
            first = n;
            break;
        }
    }
    @if ((loggedinuser != null) && (loggedinuser.Role == UserType.Administrator.ToString()))
    {
        @Html.ActionLink("Create New", "Create", new {id = first.FacultyId}, new {@class = "btn btn-success"})
    }

</p>

<table class="table table-condensed table-hover" id="datatable">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>

            <td>
                @if ((loggedinuser != null) && (loggedinuser.Role == UserType.Administrator.ToString()))
                {
                    @Html.ActionLink("Edit", "Edit", new {id = item.DepartmentId}, new {@class = "btn btn-primary"})
                }
                @Html.ActionLink("Details", "Details", new {id = item.DepartmentId}, new {@class = "btn btn-default"})
                @if ((loggedinuser != null) && (loggedinuser.Role == UserType.Administrator.ToString()))
                {
                    @Html.ActionLink("Delete", "Delete", new {id = item.DepartmentId}, new {@class = "btn btn-danger"})
                }
                <div class="btn-group">
                    <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-cogs"></i>
                        View Course(s) <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu text-left">
                        @foreach (var level in levelList)
                        {
                            <li>
                                <a href="@Url.Action("ViewCoursesForLevel", "Courses", new {levelId = level.LevelId, departmentId = item.DepartmentId})">
                                    <i class="fa fa-file-text-o"></i> @level.Name
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </td>
        </tr>
    }
    </tbody>

</table>

@section scripts {

    <script src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <script>
        $(document)
            .ready(function() {
                $('#datatable').DataTable();
            });

    </script>
}