CourseShuffle/Controllers/CourseShuffle/DepartmentsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using CoureShuffle.Data.DataContext.DataContext;
using CourseShuffle.Data.Factory.FactoryData;
using CourseShuffle.Data.Objects.Entities;
using CourseShuffle.Data.Service.Enum;

namespace CourseShuffle.Controllers.CourseShuffle
{
    public class DepartmentsController : Controller
    {
        private readonly DepartmentDataContext _db = new DepartmentDataContext();

        // GET: Departments
        public ActionResult Index()
        {
            var departments = _db.Departments.Include(d => d.Faculty);
            return View(departments.ToList());
        }

        // GET: Departments/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var department = _db.Departments.Find(id);
            if (department == null)
                return HttpNotFound();
            return View(department);
        }

        public ActionResult ViewDepartmentForFaculty(long id)
        {
            var departments = new DepartmentFactory().GetAllDepartmentsForAFaculty(id);
            return View("FacultyDepartments", departments);
        }

        // GET: Departments/Create
        public ActionResult Create(long? id)
        {
            if (id <= 0)
                id = 0;
            ViewBag.FacultyId = new SelectList(_db.Faculties, "FacultyId", "Name");
            ViewBag.Faculty = id ?? 0;

            return View();
        }

        // POST: Departments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DepartmentId,Name,Description")] Department department,
            FormCollection collectedValues)
        {
            if (ModelState.IsValid)
            {
                var loggedinuser = Session["courseshuffleloggedinuser"] as AppUser;
                var type = typeof(SubscriptionType).GetEnumName(int.Parse(collectedValues["Type"]));
                if (loggedinuser != null)
                {
                    var facultyId = Convert.ToInt64(collectedValues["FacultyId"]);
                    if (collectedValues["FacultyId"] == null)
                        facultyId = Convert.ToInt64(collectedValues["Faculty"]);
                    if (type == SubscriptionType.None.ToString())
                    {
                        department.SubscriptionStartDate = null;
                        department.SubscriptionEndDate = null;
                        department.SubscriptionType = type;
                    }
                    if (type == SubscriptionType.SingleSemester.ToString())
                    {
                        department.SubscriptionStartDate = DateTime.Now;
                        department.SubscriptionEndDate = DateTime.Now.AddMonths(6);
                        department.SubscriptionType = type;
                    }
                    if (type == SubscriptionType.CompleteSession.ToString())
                    {
                        department.SubscriptionStartDate = DateTime.Now;
                        department.SubscriptionEndDate = DateTime.Now.AddMonths(12);
                        department.SubscriptionType = type;
                    }

                    department.FacultyId = facultyId;

                    department.DateCreated = DateTime.Now;
                    department.DateLastModified = DateTime.Now;
                    department.CreatedBy = loggedinuser.AppUserId;
                    department.LastModifiedBy = loggedinuser.AppUserId;
                    _db.Departments.Add(department);
                    _db.SaveChanges();
                    TempData["department"] = "A new department has been created successfully!";
                    TempData["notificationtype"] = NotificationType.Info.ToString();
                    return RedirectToAction("Index");
                }
                TempData["department"] = "Your session has expired,Login Again!";
                TempData["notificationtype"] = NotificationType.Info.ToString();
            }

            ViewBag.FacultyId = new SelectList(_db.Faculties, "FacultyId", "Name", department.FacultyId);
            return View(department);
        }

        // GET: Departments/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var department = _db.Departments.Find(id);
            if (department == null)
                return HttpNotFound();
            ViewBag.FacultyId = new SelectList(_db.Faculties, "FacultyId", "Name", department.FacultyId);
            return View(department);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(
            [Bind(Include = "DepartmentId,Name,Description,FacultyId,CreatedBy,SubscriptionStartDate,SubscriptionEndDate,SubscriptionType")] Department department,
            FormCollection collectedValues)
        {
            if (ModelState.IsValid)
            {
                var type = typeof(SubscriptionType).GetEnumName(int.Parse(collectedValues["Type"]));
                var loggedinuser = Session["courseshuffleloggedinuser"] as AppUser;
                if (loggedinuser != null)
                {
                    if (DateTime.Now > department.SubscriptionEndDate)
                    {
                        if (type == SubscriptionType.None.ToString())
                        {
                            department.SubscriptionStartDate = null;
                            department.SubscriptionEndDate = null;
                            department.SubscriptionType = type;
                        }
                        if (type == SubscriptionType.SingleSemester.ToString())
                        {
                            department.SubscriptionStartDate = DateTime.Now;
                            department.SubscriptionEndDate = DateTime.Now.AddMonths(6);
                            department.SubscriptionType = type;
                        }
                        if (type == SubscriptionType.CompleteSession.ToString())
                        {
                            department.SubscriptionStartDate = DateTime.Now;
                            department.SubscriptionEndDate = DateTime.Now.AddMonths(12);
                            department.SubscriptionType = type;
                        }
                    }

                    department.DateCreated = Convert.ToDateTime(collectedValues["DateCreated"]);
                    department.DateLastModified = DateTime.Now;
                    department.LastModifiedBy = loggedinuser.AppUserId;
                    _db.Entry(department).State = EntityState.Modified;
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
                TempData["department"] = "Your session has expired,Login Again!";
                TempData["notificationtype"] = NotificationType.Info.ToString();
            }
            ViewBag.FacultyId = new SelectList(_db.Faculties, "FacultyId", "Name", department.FacultyId);
            return View(department);
        }

        // GET: Departments/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var department = _db.Departments.Find(id);
            if (department == null)
                return HttpNotFound();
            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            var department = _db.Departments.Find(id);
            _db.Departments.Remove(department);
            _db.SaveChanges();
            TempData["department"] = "A department has been deleted successfully!";
            TempData["notificationtype"] = NotificationType.Success.ToString();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

CourseShuffle/Controllers/CourseShuffle/FacultiesController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using CoureShuffle.Data.DataContext.DataContext;
using CourseShuffle.Data.Objects.Entities;
using CourseShuffle.Data.Service.Enum;

namespace CourseShuffle.Controllers.CourseShuffle
{
    public class FacultiesController : Controller
    {
        private readonly FacultyDataContext _db = new FacultyDataContext();
        private readonly DepartmentDataContext _dbc = new DepartmentDataContext();

        // GET: Faculties
        public ActionResult Index()
        {
            return View(_db.Faculties.ToList());
        }

        // GET: Faculties/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var faculty = _db.Faculties.Find(id);
            if (faculty == null)
                return HttpNotFound();
            return View(faculty);
        }

        // GET: Faculties/Create
        public ActionResult Create(long? id)
        {
            return View();
        }

        // POST: Faculties/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FacultyId,Name,Description")] Faculty faculty)
        {
            if (ModelState.IsValid)
            {
                var loggedinuser = Session["courseshuffleloggedinuser"] as AppUser;
                if (loggedinuser != null)
                {
                    faculty.DateCreated = DateTime.Now;
                    faculty.DateLastModified = DateTime.Now;
                    faculty.CreatedBy = loggedinuser.AppUserId;
                    faculty.LastModifiedBy = loggedinuser.AppUserId;
                    _db.Faculties.Add(faculty);
                    _db.SaveChanges();
                    TempData["faculty"] = "A new faculty has been created successfully!";
                    TempData["notificationtype"] = NotificationType.Success.ToString();
                    return RedirectToAction("Index");
                }
                TempData["faculty"] = "Your session has expired,Login Again!";
                TempData["notificationtype"] = NotificationType.Info.ToString();
            }

            return View(faculty);
        }

        // GET: Faculties/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var faculty = _db.Faculties.Find(id);
            if (faculty == null)
                return HttpNotFound();
            return View(faculty);
        }

        // POST: Faculties/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FacultyId,Name,Description")] Faculty faculty,
            FormCollection collectedValues)
        {
            if (ModelState.IsValid)
            {
                var loggedinuser = Session["courseshuffleloggedinuser"] as AppUser;
                if (loggedinuser != null)
                {
                    faculty.DateCreated = Convert.ToDateTime(collectedValues["DateCreated"]);
                    faculty.DateLastModified = DateTime.Now;
                    faculty.LastModifiedBy = loggedinuser.AppUserId;
                    _db.Entry(faculty).State = EntityState.Modified;
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
                TempData["faculty"] = "Your session has expired,Login Again!";
                TempData["notificationtype"] = NotificationType.Info.ToString();
            }
            return View(faculty);
        }

        // GET: Faculties/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var faculty = _db.Faculties.Find(id);
            if (faculty == null)
                return HttpNotFound();
            return View(faculty);
        }

        // POST: Faculties/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            var faculty = _db.Faculties.Find(id);
            _db.Faculties.Remove(faculty);
            _db.SaveChanges();
            TempData["faculty"] = "A faculty has been deleted successfully!";
            TempData["notificationtype"] = NotificationType.Success.ToString();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

CourseShuffle/Views/Faculties/Create.cshtml
@using CourseShuffle.Data.Service.Enum
@model CourseShuffle.Data.Objects.Entities.Faculty

@{
    ViewBag.Title = "Create";
}
<div class="container">
    <div class="row">
        <div class="panel panel-flat">
            @if (TempData["faculty"] != null)
            {
                if (TempData["notificationtype"].Equals(NotificationType.Success.ToString()))
                {
                    <div class="alert alert-success alert-dismissable" style="height: 30px">@TempData["faculty"]</div>
                }
                else if (TempData["notificationtype"].Equals(NotificationType.Danger.ToString()))
                {
                    <div class="alert alert-danger alert-dismissable" style="height: 30px">@TempData["faculty"]</div>
                }
                else if (TempData["notificationtype"].Equals(NotificationType.Info.ToString()))
                {
                    <div class="alert alert-info alert-dismissable" style="height: 30px">@TempData["faculty"]</div>
                }
            }
            <div class="panel-body">
                <div class="col-md-12">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <h4>Faculty</h4>
                            <hr/>
                            @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                            <div class="form-group col-md -12">
                                @Html.LabelFor(model => model.Name, new {@class = "control-label col-md-3"})
                                <div class="col-sm-6 col-md-9">
                                    @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
                                    @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
                                </div>
                            </div>

                            <div class="form-group col-md-12">
                                @Html.LabelFor(model => model.Description, new {@class = "control-label col-md-3"})
                                <div class="col-sm-6 col-md-9">
                                    @Html.EditorFor(model => model.Description, new {htmlAttributes = new {@class = "form-control"}})
                                    @Html.ValidationMessageFor(model => model.Description, "", new {@class = "text-danger"})
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <a href="@Url.Action("Index", "Faculties")" class="btn btn-default pull-left">Cancel</a>
                                    <input type="submit" value="Create" class="btn btn-primary pull-right"/>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

CourseShuffle/Views/Faculties/Delete.cshtml
@model CourseShuffle.Data.Objects.Entities.Faculty

@{
    ViewBag.Title = "Delete";
}

<h2></h2>

<h3>Are you sure you want to delete this?</h3>
<h4>Faculty</h4>
<div class="container">
    <div class="row">
        <div class="panel panel-flat">

            <div class="panel-body">
                <div class="col-md-12">
                    <div class="form-group col-md-12">
                        <div class="col-md-3 detailsDiv">
                            @Html.DisplayNameFor(model => model.Name)
                        </div>

                        <div class="col-md-9">
                            @Html.DisplayFor(model => model.Name)
                        </div>
                    </div>

                    <div class="form-group col-md-12">
                        <div class="col-md-3 detailsDiv">
                            @Html.DisplayNameFor(model => model.Description)
                        </div>

                        <div class="col-md-9 ">
                            @Html.DisplayFor(model => model.Description)
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger pull-right"/> |
            @Html.ActionLink("Back to List", "Index", null, new {@class = "btn btn-default pull-left"})
        </div>
    }
</div>

CourseShuffle/Views/Faculties/Details.cshtml
@using CourseShuffle.Data.Factory.FactoryData
@model CourseShuffle.Data.Objects.Entities.Faculty

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<div class="container">
    <div class="row">
        <div class="panel panel-flat">

            <div class="panel-body">
                <div class="col-md-12">
                    <div class="form-group col-md-12">
                        <div class="col-md-3 detailsDiv">
                            @Html.DisplayNameFor(model => model.Name)
                        </div>

                        <div class="col-md-9">
                            @Html.DisplayFor(model => model.Name)
                        </div>
                    </div>

                    <div class="form-group col-md-12">
                        <div class="col-md-3 detailsDiv">
                            @Html.DisplayNameFor(model => model.Description)
                        </div>

                        <div class="col-md-9 ">
                            @Html.DisplayFor(model => model.Description)
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <div class="col-md-3 detailsDiv">
                            @Html.DisplayNameFor(model => model.DateCreated)
                        </div>

                        <div class="col-md-9 ">
                            @Html.DisplayFor(model => model.DateCreated)
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <div class="col-md-3 detailsDiv">
                            @Html.DisplayNameFor(model => model.DateLastModified)
                        </div>

                        <div class="col-md-9 ">
                            @Html.DisplayFor(model => model.DateLastModified)
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <div class="col-md-3 detailsDiv">
                            @Html.DisplayNameFor(model => model.CreatedBy)
                        </div>

                        <div class="col-md-9 ">
                            @(new AppUserFactory().GetAppUserById((int) Model.CreatedBy).DisplayName)
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <div class="col-md-3 detailsDiv">
                            @Html.DisplayNameFor(model => model.LastModifiedBy)
                        </div>

                        <div class="col-md-9 ">
                            @(new AppUserFactory().GetAppUserById((int) Model.LastModifiedBy).DisplayName)
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <p>
        @Html.ActionLink("Edit", "Edit", new {id = Model.FacultyId}, new {@class = "btn btn-primary"}) |
        @Html.ActionLink("Back to List", "Index", null, new {@class = "btn btn-default"})
    </p>
</div>

CourseShuffle/Views/Faculties/Edit.cshtml
@using CourseShuffle.Data.Service.Enum
@model CourseShuffle.Data.Objects.Entities.Faculty

@{
    ViewBag.Title = "Edit";
}
@if (TempData["faculty"] != null)
{
    if (TempData["notificationtype"].Equals(NotificationType.Success.ToString()))
    {
        <div class="alert alert-success alert-dismissable" style="height: 30px">@TempData["faculty"]</div>
    }
    else if (TempData["notificationtype"].Equals(NotificationType.Danger.ToString()))
    {
        <div class="alert alert-danger alert-dismissable" style="height: 30px">@TempData["faculty"]</div>
    }
    else if (TempData["notificationtype"].Equals(NotificationType.Info.ToString()))
    {
        <div class="alert alert-info alert-dismissable" style="height: 30px">@TempData["faculty"]</div>
    }
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Faculty</h4>
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        @Html.HiddenFor(model => model.FacultyId)
        @Html.HiddenFor(model => model.DateCreated)
        @Html.HiddenFor(model => model.CreatedBy)

        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.Name, new {@class = "control-label col-md-3"})
            <div class="col-sm-6 col-md-9">
                @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.Description, new {@class = "control-label col-md-3"})
            <div class="col-sm-6 col-md-9">
                @Html.EditorFor(model => model.Description, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Description, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <a href="@Url.Action("Index", "Faculties")" class="btn btn-default pull-left">Cancel</a>
                <input type="submit" value="Save" class="btn btn-primary pull-right"/>
            </div>
        </div>
    </div>
}

CourseShuffle/Views/Faculties/Index.cshtml
@using CourseShuffle.Data.Objects.Entities
@using CourseShuffle.Data.Service.Enum
@model IEnumerable<CourseShuffle.Data.Objects.Entities.Faculty>

@{
    ViewBag.Title = "Index";
    var loggedinuser = Session["courseshuffleloggedinuser"] as AppUser;
}
@section css{
    <link href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" rel="stylesheet"/>
}
<h2></h2>
@if (TempData["faculty"] != null)
{
    if (TempData["notificationtype"].Equals(NotificationType.Success.ToString()))
    {
        <div class="alert alert-success alert-dismissable" style="height: 30px">@TempData["faculty"]</div>
    }
    else if (TempData["notificationtype"].Equals(NotificationType.Danger.ToString()))
    {
        <div class="alert alert-danger alert-dismissable" style="height: 30px">@TempData["faculty"]</div>
    }
    else if (TempData["notificationtype"].Equals(NotificationType.Info.ToString()))
    {
        <div class="alert alert-info alert-dismissable" style="height: 30px">@TempData["faculty"]</div>
    }
}
<p>
    @if ((loggedinuser != null) && (loggedinuser.Role == UserType.Administrator.ToString()))
    {
        @Html.ActionLink("Add Faculty", "Create", null, new {@class = "btn btn-success"})
    }
</p>

<div class="table-responsive">
    <table class="table table-condensed table-hover" id="datatable">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>Action</th>
        </tr>
        </thead>

        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new {id = item.FacultyId}, new {@class = "btn btn-default"}) |
                    @*@Html.ActionLink("Details", "Details", new { id=item.FacultyId }, new { @class = "btn btn-default" }) |*@
                    @Html.ActionLink("Delete", "Delete", new {id = item.FacultyId}, new {@class = "btn btn-danger"}) |
                    @Html.ActionLink("Add Department", "Create", "Departments", new {id = item.FacultyId}, new {@class = "btn btn-warning"}) |
                    @Html.ActionLink("View Departments", "ViewDepartmentForFaculty", "Departments", new {id = item.FacultyId}, new {@class = "btn btn-primary"})
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>
@section scripts {

    <script src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <script>
        $(document)
            .ready(function() {
                $('#datatable').DataTable();
            });

    </script>
}