CourseShuffle/Controllers/CourseShuffle/CategoriesController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using CoureShuffle.Data.DataContext.DataContext;
using CourseShuffle.Data.Factory.FactoryData;
using CourseShuffle.Data.Objects.Entities;
using CourseShuffle.Data.Service.Enum;

namespace CourseShuffle.Controllers.CourseShuffle
{
    public class CategoriesController : Controller
    {
        private readonly CategoryDataContext db = new CategoryDataContext();

        // GET: Categories
        public ActionResult Index()
        {
            var categories = db.Categories.Include(c => c.Department);
            return View(categories.ToList());
        }
        /// <summary>
        ///     Sends Json responds object to view with categories of the department requested via an Ajax call
        /// </summary>
        /// <param name="id"> state id</param>
        /// <returns>lgas</returns>
        public JsonResult GetCategoryForDepartment(int id)
        {
            var categories = new CategoryFactory().GetDepartmentCategories(id);
            return Json(categories, JsonRequestBehavior.AllowGet);
        }
        // GET: Categories/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var category = db.Categories.Find(id);
            if (category == null)
                return HttpNotFound();
            return View(category);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Name");
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoryId,Name,DepartmentId")] Category category)
        {
            var loggedinuser = Session["courseshuffleloggedinuser"] as AppUser;
            if (ModelState.IsValid)
            {
                if ((loggedinuser != null) && (loggedinuser.Role == UserType.Administrator.ToString()))
                {
                    category.DateCreated = DateTime.Now;
                    category.DateLastModified = DateTime.Now;
                    category.CreatedBy = loggedinuser.AppUserId;
                    category.LastModifiedBy = loggedinuser.AppUserId;
                    db.Categories.Add(category);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                TempData["category"] = "A new category has been created!";
                TempData["notificationtype"] = NotificationType.Success.ToString();
                return RedirectToAction("Index");
            }

            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Name", category.DepartmentId);
            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var category = db.Categories.Find(id);
            if (category == null)
                return HttpNotFound();
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Name", category.DepartmentId);
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(
            [Bind(Include = "CategoryId,Name,DepartmentId,CreatedBy,DateCreated")] Category category)
        {
            var loggedinuser = Session["courseshuffleloggedinuser"] as AppUser;
            if (ModelState.IsValid)
            {
                if ((loggedinuser != null) && (loggedinuser.Role == UserType.Administrator.ToString()))
                {
                    category.DateLastModified = DateTime.Now;
                    category.LastModifiedBy = loggedinuser.AppUserId;
                    db.Entry(category).State = EntityState.Modified;
                    db.SaveChanges();
                    TempData["category"] = "The category has been modified!";
                    TempData["notificationtype"] = NotificationType.Success.ToString();
                    return RedirectToAction("Index");
                }
                TempData["category"] = "Your session has expired,Login Again!";
                TempData["notificationtype"] = NotificationType.Info.ToString();
                return RedirectToAction("Index");
            }
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Name", category.DepartmentId);
            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var category = db.Categories.Find(id);
            if (category == null)
                return HttpNotFound();
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            var category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                db.Dispose();
            base.Dispose(disposing);
        }
    }
}

CourseShuffle/Controllers/CourseShuffle/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CoureShuffle.Data.DataContext.DataContext;
using CourseShuffle.Data.Objects.Entities;
using CourseShuffle.Data.Service.Enum;
using CourseShuffle.Data.Service.FileUploader;

namespace CourseShuffle.Controllers.CourseShuffle
{
    public class ProjectsController : Controller
    {
        private ProjectDataContext _db = new ProjectDataContext();

        // GET: Projects
        public ActionResult Index()
        {
            var projects = _db.Projects.Include(p => p.Session);
            return View(projects.ToList());
        }
        // GET: Projects
        public ActionResult GetProjectsForDepartment(long departmentId)
        {
            var projects = _db.Projects.Include(p => p.Session).Where(n=>n.DepartmentId == departmentId );
            return View("Index",projects.ToList());
        }

        // GET: Projects/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = _db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // GET: Projects/Create
        public ActionResult Create()
        {
            ViewBag.SessionId = new SelectList(_db.Sessions, "SessionId", "Name");
            ViewBag.DepartmentId = new SelectList(_db.Departments, "DepartmentId", "Name");
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProjectId,Title,Author,StartDate,EndDate,CategoryId,SessionId,DepartmentId")] Project project,FormCollection collectedValues)
        {
            var loggedinuser = Session["courseshuffleloggedinuser"] as AppUser;
            if (ModelState.IsValid)
            {
                if (loggedinuser != null)
                {
                    HttpPostedFileBase document = Request.Files["document"];
                    project.Document = new FileUploader().UploadFile(document,
    UploadType.ProjectDocument.ToString());
                    project.DateCreated = DateTime.Now;
                    project.DateLastModified = DateTime.Now;
                    project.CreatedBy = loggedinuser.AppUserId;
                    project.LastModifiedBy = loggedinuser.AppUserId;
                    _db.Projects.Add(project);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
                TempData["project"] = "Your session has expired,Login Again!";
                TempData["notificationtype"] = NotificationType.Info.ToString();
                return RedirectToAction("Index");
            }

            ViewBag.SessionId = new SelectList(_db.Sessions, "SessionId", "Name", project.SessionId);
            ViewBag.DepartmentId = new SelectList(_db.Departments, "DepartmentId", "Name", project.DepartmentId);
            return View(project);
        }

        // GET: Projects/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = _db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            ViewBag.SessionId = new SelectList(_db.Sessions, "SessionId", "Name", project.SessionId);
            ViewBag.DepartmentId = new SelectList(_db.Departments, "DepartmentId", "Name",project.DepartmentId);
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProjectId,Title,Author,CategoryId,DepartmentId,Document,SessionId,CreatedBy")] Project project,FormCollection collectedValues)
        {
            var loggedinuser = Session["courseshuffleloggedinuser"] as AppUser;
            if (ModelState.IsValid)
            {
                if (loggedinuser != null)
                {
                    project.StartDate = Convert.ToDateTime(collectedValues["StartDate"]);
                    project.EndDate = Convert.ToDateTime(collectedValues["EndDate"]);
                    project.DateCreated = Convert.ToDateTime(collectedValues["DateCreated"]);
                    project.DateLastModified = DateTime.Now;
                    project.LastModifiedBy = loggedinuser.AppUserId;
                    _db.Entry(project).State = EntityState.Modified;
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
                TempData["project"] = "Your session has expired,Login Again!";
                TempData["notificationtype"] = NotificationType.Info.ToString();
                return RedirectToAction("Index");
            }
    
                ViewBag.SessionId = new SelectList(_db.Sessions, "SessionId", "Name", project.SessionId);
            ViewBag.DepartmentId = new SelectList(_db.Departments, "DepartmentId", "Name", project.DepartmentId);
            return View(project);
        }

        // GET: Projects/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = _db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Project project = _db.Projects.Find(id);
            _db.Projects.Remove(project);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CourseShuffle/Views/Projects/Create.cshtml
@model CourseShuffle.Data.Objects.Entities.Project

@{
    ViewBag.Title = "Create";
}

<h2></h2>
@section css{
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="~/Scripts/plugins/Form/css/select2.css" rel="stylesheet"/>
}
@using (Html.BeginForm("Create", "Projects", FormMethod.Post, new {enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4></h4>
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.Title, new {@class = "control-label col-md-3"})
            <div class="col-sm-6 col-md-9">
                @Html.EditorFor(model => model.Title, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Title, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.Author, new {@class = "control-label col-md-3"})
            <div class="col-sm-6 col-md-9">
                @Html.EditorFor(model => model.Author, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Author, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.StartDate, new {@class = "control-label col-md-3"})
            <div class="col-md-9">
                @Html.EditorFor(model => model.StartDate, new {htmlAttributes = new {@class = "form-control datepicker"}})
                @Html.ValidationMessageFor(model => model.StartDate, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.EndDate, new {@class = "control-label col-md-3"})
            <div class="col-sm-6 col-md-9">
                @Html.EditorFor(model => model.EndDate, new {htmlAttributes = new {@class = "form-control datepicker"}})
                @Html.ValidationMessageFor(model => model.EndDate, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.DepartmentId, "Department", new {@class = "control-label col-md-3"})
            <div class="col-sm-6 col-md-9">
                @Html.DropDownListFor(model => model.DepartmentId, (SelectList) ViewBag.DepartmentId, new {@class = "form-control select-dropdown", id = "department"})
                @Html.ValidationMessageFor(model => model.DepartmentId, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.Category, new {@class = "control-label col-md-3"})
            <div class="col-sm-6 col-md-9">
                @Html.DropDownListFor(model => model.CategoryId, new SelectList(string.Empty, "Value", "Text"), new {@class = "form-control select-dropdown", id = "category"})
            </div>
        </div>
        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.SessionId, "Session", new {@class = "control-label col-md-3"})
            <div class="col-sm-6 col-md-9">
                @Html.DropDownList("SessionId", null, new {@class = "form-control select-dropdown"})
                @Html.ValidationMessageFor(model => model.SessionId, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.Document, new {@class = "control-label col-md-3"})
            <div class="col-sm-6 col-md-9">
                <input type="file" name="document" id="document" style="width: 100%;"/>
                @Html.ValidationMessageFor(model => model.Document, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                @Html.ActionLink("Back to List", "Index", null, new {@class = "btn btn-default pull-left"})
                <input type="submit" value="Create" class="btn btn-primary pull-right"/>
            </div>
        </div>
    </div>
}
@section scripts{
    <script src="~/Scripts/plugins/Form/js/select2.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(document)
            .ready(function() {

                // Init select2 for dropdown select
                $('.select-dropdown').select2();
                $(function() {
                    $('.datepicker')
                        .datepicker({
                            format: 'yyyy',
                            viewMode: 'years',
                            minViewMode: 'years',
                            endDate: new Date()
                        });
                });
                //checks if the state has a value before displaying assigned lga
                if ($('#department').val() != '') {
                    getCategoriesForDepartment();
                }

                //loads assigned lga for state on change/select
                $('#department').on('change', function() { getCategoriesForDepartment(); });

                //Ajax call for Lga assigned to state
                function getCategoriesForDepartment() {

                    $("#category").empty();
                    $.ajax({
                        type: 'GET',
                        url: '@Url.Action("GetCategoryForDepartment", "Categories")',
                        dataType: 'json',
                        data: { id: $("#department").val() },
                        success: function(category) {

                            $.each(category,
                                function(i, category) {
                                    $("#category")
                                        .append('<option value="' +
                                            category.CategoryId +
                                            '">' +
                                            category.Name +
                                            '</option>');
                                });
                            console.log($("#category").val());
                        },
                        error: function(ex) {
                            alert('Failed to retrieve category.' + ex);
                        }
                    });
                }
            });
    </script>
}

CourseShuffle/Views/Projects/Delete.cshtml
@using CourseShuffle.Data.Factory.FactoryData
@model CourseShuffle.Data.Objects.Entities.Project

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <div class="row">
        <div class="panel panel-flat">

            <div class="panel-body">
                <div class="col-md-12">
                    <div class="form-group col-md-12">
                        <div class="col-md-3 detailsDiv">
                            @Html.DisplayNameFor(model => model.Title)
                        </div>

                        <div class="col-md-9">
                            @Html.DisplayFor(model => model.Title)
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <div class="col-md-3 detailsDiv">
                            @Html.DisplayNameFor(model => model.Author)
                        </div>

                        <div class="col-md-9 ">
                            @Html.DisplayFor(model => model.Author)
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <div class="col-md-3 detailsDiv">
                            @Html.DisplayNameFor(model => model.Category)
                        </div>

                        <div class="col-md-9 ">
                            @Html.DisplayFor(model => model.Category)
                        </div>
                    </div>

                    <div class="form-group col-md-12">
                        <div class="col-md-3 detailsDiv">
                            @Html.DisplayNameFor(model => model.Department)
                        </div>

                        <div class="col-md-9 ">
                            @(new DepartmentFactory().GetAppUserDepartmet(Model.DepartmentId).Name)
                        </div>
                    </div>

                    <div class="form-group col-md-12">
                        <div class="col-md-3 detailsDiv">
                            @Html.DisplayNameFor(model => model.Session)
                        </div>

                        <div class="col-md-9 ">
                            @(new SessionFactory().GetSessionById((int) Model.SessionId).Name)
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <div class="col-md-3">
                            @Html.DisplayNameFor(model => model.DateCreated)
                        </div>

                        <div class="col-md-9">
                            @Html.DisplayFor(model => model.DateCreated)
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <div class="col-md-3">
                            @Html.DisplayNameFor(model => model.DateLastModified)
                        </div>

                        <div class="col-md-9">
                            @Html.DisplayFor(model => model.DateLastModified)
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <div class="col-md-3">
                            @Html.DisplayNameFor(model => model.CreatedBy)
                        </div>

                        <div class="col-md-9">
                            @(new AppUserFactory().GetAppUserById((int) Model.CreatedBy).DisplayName)
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <div class="col-md-3">
                            @Html.DisplayNameFor(model => model.LastModifiedBy)
                        </div>

                        <div class="col-md-9">
                            @(new AppUserFactory().GetAppUserById((int) Model.LastModifiedBy).DisplayName)
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger"/> |
            @Html.ActionLink("Back to List", "Index", null, new {@class = "btn btn-default"})
        </div>
    }
</div>

CourseShuffle/Views/Projects/Edit.cshtml
@model CourseShuffle.Data.Objects.Entities.Project

@{
    ViewBag.Title = "Edit";
}

<h2></h2>
@section css{
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="~/Scripts/plugins/Form/css/select2.css" rel="stylesheet"/>
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Project</h4>
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        @Html.HiddenFor(model => model.ProjectId)
        @Html.HiddenFor(model => model.CreatedBy)
        @Html.HiddenFor(model => model.LastModifiedBy)
        @Html.HiddenFor(model => model.DepartmentId)
        @Html.HiddenFor(model => model.Document)
        @Html.HiddenFor(model => model.DateCreated)

        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.Title, new {@class = "control-label col-md-3"})
            <div class="col-sm-6 col-md-9">
                @Html.EditorFor(model => model.Title, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Title, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.Author, new {@class = "control-label col-md-3"})
            <div class="col-sm-6 col-md-9">
                @Html.EditorFor(model => model.Author, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Author, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.StartDate, new {@class = "control-label col-md-3"})
            <div class="col-md-9">
                @Html.EditorFor(model => model.StartDate, new {htmlAttributes = new {@class = "form-control datepicker"}})
                @Html.ValidationMessageFor(model => model.StartDate, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.EndDate, new {@class = "control-label col-md-3"})
            <div class="col-sm-6 col-md-9">
                @Html.EditorFor(model => model.EndDate, new {htmlAttributes = new {@class = "form-control datepicker"}})
                @Html.ValidationMessageFor(model => model.EndDate, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.DepartmentId, "Department", new {@class = "control-label col-md-3"})
            <div class="col-sm-6 col-md-9">
                @Html.DropDownListFor(model => model.Category.CategoryId, (SelectList) ViewBag.DepartmentId, new {@class = "form-control select-dropdown", id = "department"})
                @Html.ValidationMessageFor(model => model.DepartmentId, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.Category, new {@class = "control-label col-md-3"})
            <div class="col-sm-6 col-md-9">
                @Html.DropDownListFor(model => model.CategoryId, new SelectList(string.Empty, "Value", "Text"), new {@class = "form-control select-dropdown", id = "category"})
            </div>
        </div>
        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.SessionId, "SessionId", new {@class = "control-label col-md-3"})
            <div class="col-sm-6 col-md-9">
                @Html.DropDownList("SessionId", null, new {@class = "form-control select-dropdown"})
                @Html.ValidationMessageFor(model => model.SessionId, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @Html.ActionLink("Back to List", "Index", null, new {@class = "btn btn-default pull-left"})
                <input type="submit" value="Create" class="btn btn-primary pull-right"/>
            </div>
        </div>
    </div>
}
@section scripts{
    <script src="~/Scripts/plugins/Form/js/select2.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(document)
            .ready(function() {

                // Init select2 for dropdown select
                $('.select-dropdown').select2();
                $(function() {
                    $('.datepicker')
                        .datepicker({
                            format: 'yyyy',
                            viewMode: 'years',
                            minViewMode: 'years',
                            endDate: new Date()
                        });
                });
                //checks if the state has a value before displaying assigned lga
                if ($('#department').val() != '') {
                    getCategoriesForDepartment();
                }

                //loads assigned lga for state on change/select
                $('#department').on('change', function() { getCategoriesForDepartment(); });

                //Ajax call for Lga assigned to state
                function getCategoriesForDepartment() {

                    $("#category").empty();
                    $.ajax({
                        type: 'GET',
                        url: '@Url.Action("GetCategoryForDepartment", "Categories")',
                        dataType: 'json',
                        data: { id: $("#department").val() },
                        success: function(category) {

                            $.each(category,
                                function(i, category) {
                                    $("#category")
                                        .append('<option value="' +
                                            category.CategoryId +
                                            '">' +
                                            category.Name +
                                            '</option>');
                                });
                            console.log($("#category").val());
                        },
                        error: function(ex) {
                            alert('Failed to retrieve category.' + ex);
                        }
                    });
                }
            })
    </script>
}